# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'wdKuaiKe_iOS' do 

pod 'SDAutoLayout', '~> 2.1.4'
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.1'
pod 'MJRefresh', '~> 3.1.12'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'IQKeyboardManager', '~> 4.0.4'
pod 'WeiboSDK', '~> 3.1.3'
pod 'MJExtension', '~> 3.0.13'
pod 'SDCycleScrollView', '~> 1.65'
pod 'AMapLocation', '~> 2.1.0'
pod 'AMapSearch', '~> 4.1.0'
pod 'AMapNavi', '~> 2.1.0'


  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for wdKuaiKe_iOS

  target 'wdKuaiKe_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'wdKuaiKe_iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
